export const CATEGORIES = [
  { id: 'all', nameNe: 'सबै सामान', nameEn: 'All Items', icon: '🛒' },
  { id: 'vegetables', nameNe: 'तरकारी र फलफूल', nameEn: 'Vegetables & Fruits', icon: '🥔' },
  { id: 'staples', nameNe: 'चामल, दाल र तेल', nameEn: 'Rice, Dal & Oil', icon: '🌾' },
  { id: 'dairy', nameNe: 'दूध र दही', nameEn: 'Milk & Dairy', icon: '🥛' },
  { id: 'snacks', nameNe: 'बिस्कुट र चाउचाउ', nameEn: 'Biscuits & Snacks', icon: '🍜' },
  { id: 'beverages', nameNe: 'चिया, कफी र पेय', nameEn: 'Tea & Beverages', icon: '☕' },
  { id: 'spices', nameNe: 'मसला र नुन', nameEn: 'Spices & Salt', icon: '🧂' },
  { id: 'household', nameNe: 'साबुन र घरायसी', nameEn: 'Soap & Household', icon: '🧼' },
];

export const INITIAL_SHOPS = [
  {
    id: 'shop-1',
    shopType: 'grocery',
    ownerId: null,
    name: 'राम किराना पसल',
    nameEn: 'Ram Kirana Pasal',
    ownerName: 'राम बहादुर श्रेष्ठ',
    phone: '9841234567',
    address: 'नयाँ बानेश्वर, काठमाडौं',
    addressEn: 'New Baneshwor, Kathmandu',
    distanceKm: 0.8,
    rating: 4.8,
    reviewCount: 34,
    isOpen: true,
    openingTime: '06:00',
    closingTime: '21:00',
    deliveryAvailable: true,
    deliveryStartTime: '07:00',
    deliveryEndTime: '20:00',
    maxDeliveryDistanceKm: 6,
    minOrderAmount: 100,
    deliveryModel: 'basePlusKm', // 'basePlusKm' | 'distanceSlabs'
    baseDeliveryCharge: 25,
    perKmCharge: 15,
    deliverySlabs: [
      { maxKm: 1, charge: 20 },
      { maxKm: 3, charge: 40 },
      { maxKm: 5, charge: 70 },
      { maxKm: 10, charge: 120 }
    ],
    deliveryPersons: ['पसले आफैं (Ram)', 'रमेश (Ramesh - 9801122334)', 'सुमन (Suman - 9812233445)'],
    paymentSettings: {
      codEnabled: true,
      esewaEnabled: true,
      esewaId: '9841234567',
      khaltiEnabled: true,
      khaltiId: '9841234567',
      bankTransferEnabled: true,
      bankName: 'Nabil Bank Ltd.',
      bankAccountHolder: 'Ram Bahadur Shrestha',
      bankAccountNumber: '01201017500123',
      qrImage: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=epay:ramkirana@nabilbank'
    },
    image: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'shop-2',
    shopType: 'general',
    ownerId: null,
    name: 'सीता जनरल स्टोर',
    nameEn: 'Sita General Store',
    ownerName: 'सीता देवी शर्मा',
    phone: '9856012345',
    address: 'लेकसाइड मार्ग, पोखरा',
    addressEn: 'Lakeside Road, Pokhara',
    distanceKm: 1.5,
    rating: 4.9,
    reviewCount: 42,
    isOpen: true,
    openingTime: '06:30',
    closingTime: '21:30',
    deliveryAvailable: true,
    deliveryStartTime: '07:30',
    deliveryEndTime: '20:30',
    maxDeliveryDistanceKm: 8,
    minOrderAmount: 150,
    deliveryModel: 'distanceSlabs',
    baseDeliveryCharge: 30,
    perKmCharge: 15,
    deliverySlabs: [
      { maxKm: 1, charge: 25 },
      { maxKm: 3, charge: 45 },
      { maxKm: 6, charge: 80 }
    ],
    deliveryPersons: ['सीता देवी', 'सन्तोष (Santosh - 9803344556)'],
    paymentSettings: {
      codEnabled: true,
      esewaEnabled: true,
      esewaId: '9856012345',
      khaltiEnabled: true,
      khaltiId: '9856012345',
      bankTransferEnabled: true,
      bankName: 'Global IME Bank',
      bankAccountHolder: 'Sita Devi Sharma',
      bankAccountNumber: '10501010045678',
      qrImage: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=epay:sitastore@globalime'
    },
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'shop-3',
    shopType: 'grocery',
    ownerId: null,
    name: 'जानकी ग्रोसरी',
    nameEn: 'Janaki Grocery & Kirana',
    ownerName: 'राजेन्द्र महतो',
    phone: '9819876543',
    address: 'स्टेशन रोड, जनकपुरधाम',
    addressEn: 'Station Road, Janakpurdham',
    distanceKm: 2.2,
    rating: 4.7,
    reviewCount: 28,
    isOpen: true,
    openingTime: '07:00',
    closingTime: '20:30',
    deliveryAvailable: true,
    deliveryStartTime: '08:00',
    deliveryEndTime: '19:30',
    maxDeliveryDistanceKm: 5,
    minOrderAmount: 80,
    deliveryModel: 'basePlusKm',
    baseDeliveryCharge: 20,
    perKmCharge: 12,
    deliverySlabs: [
      { maxKm: 1, charge: 20 },
      { maxKm: 3, charge: 35 },
      { maxKm: 5, charge: 60 }
    ],
    deliveryPersons: ['राजेन्द्र महतो', 'अमित (Amit - 9811122233)'],
    paymentSettings: {
      codEnabled: true,
      esewaEnabled: true,
      esewaId: '9819876543',
      khaltiEnabled: true,
      khaltiId: '9819876543',
      bankTransferEnabled: true,
      bankName: 'Nepal Investment Mega Bank',
      bankAccountHolder: 'Rajendra Mahato',
      bankAccountNumber: '04502010088990',
      qrImage: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=epay:janakigrocery@nimb'
    },
    image: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'shop-4',
    shopType: 'sweets',
    ownerId: null,
    name: 'पौडेल मिठाई भण्डार',
    nameEn: 'Poudel Sweets & Bakery',
    ownerName: 'गीता पौडेल',
    phone: '9845098765',
    address: 'दरबारमार्ग, काठमाडौं',
    addressEn: 'Durbar Marg, Kathmandu',
    distanceKm: 1.1,
    rating: 4.9,
    reviewCount: 51,
    isOpen: true,
    openingTime: '07:00',
    closingTime: '21:00',
    deliveryAvailable: true,
    deliveryStartTime: '08:00',
    deliveryEndTime: '20:00',
    maxDeliveryDistanceKm: 6,
    minOrderAmount: 120,
    deliveryModel: 'basePlusKm',
    baseDeliveryCharge: 30,
    perKmCharge: 15,
    deliverySlabs: [
      { maxKm: 1, charge: 25 },
      { maxKm: 3, charge: 45 },
      { maxKm: 5, charge: 75 }
    ],
    deliveryPersons: ['गीता पौडेल', 'बिनोद (Binod - 9807766554)'],
    paymentSettings: {
      codEnabled: true,
      esewaEnabled: true,
      esewaId: '9845098765',
      khaltiEnabled: true,
      khaltiId: '9845098765',
      bankTransferEnabled: true,
      bankName: 'Himalayan Bank Ltd.',
      bankAccountHolder: 'Gita Poudel',
      bankAccountNumber: '01903010077665',
      qrImage: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=epay:poudelsweets@himalayan'
    },
    image: 'https://images.unsplash.com/photo-1606471191009-63994c53433b?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'shop-5',
    shopType: 'hardware',
    ownerId: null,
    name: 'शर्मा हार्डवेयर एन्ड पेन्ट्स',
    nameEn: 'Sharma Hardware & Paints',
    ownerName: 'मोहन शर्मा',
    phone: '9812611223',
    address: 'बुटवल रोड, भैरहवा',
    addressEn: 'Butwal Road, Bhairahawa',
    distanceKm: 2.6,
    rating: 4.6,
    reviewCount: 19,
    isOpen: true,
    openingTime: '07:30',
    closingTime: '19:30',
    deliveryAvailable: true,
    deliveryStartTime: '08:30',
    deliveryEndTime: '18:30',
    maxDeliveryDistanceKm: 10,
    minOrderAmount: 200,
    deliveryModel: 'distanceSlabs',
    baseDeliveryCharge: 40,
    perKmCharge: 20,
    deliverySlabs: [
      { maxKm: 2, charge: 40 },
      { maxKm: 5, charge: 80 },
      { maxKm: 10, charge: 150 }
    ],
    deliveryPersons: ['मोहन शर्मा', 'राजु (Raju - 9819988776)'],
    paymentSettings: {
      codEnabled: true,
      esewaEnabled: true,
      esewaId: '9812611223',
      khaltiEnabled: true,
      khaltiId: '9812611223',
      bankTransferEnabled: true,
      bankName: 'Prabhu Bank Ltd.',
      bankAccountHolder: 'Mohan Sharma',
      bankAccountNumber: '06601010033221',
      qrImage: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=epay:sharmahardware@prabhu'
    },
    image: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&q=80',
  }
];

export const INITIAL_PRODUCTS = [
  // Vegetables
  {
    id: 'prod-1',
    shopId: 'shop-1',
    aliasId: 'potato',
    nameNe: 'आलु (लोकल)',
    nameEn: 'Fresh Potato',
    category: 'vegetables',
    price: 80,
    unit: 'kg',
    stock: 35,
    minStock: 5,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'ताजा मुडेको रातो आलु',
    brand: 'Local Farm'
  },
  {
    id: 'prod-2',
    shopId: 'shop-1',
    aliasId: 'onion',
    nameNe: 'प्याज (रातो)',
    nameEn: 'Red Onion',
    category: 'vegetables',
    price: 90,
    unit: 'kg',
    stock: 20,
    minStock: 4,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1508747703725-719777637510?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'राम्रो सुकेको रातो प्याज',
    brand: 'Local'
  },
  {
    id: 'prod-3',
    shopId: 'shop-1',
    aliasId: 'tomato',
    nameNe: 'गोलभेंडा (टमाटर)',
    nameEn: 'Fresh Tomato',
    category: 'vegetables',
    price: 70,
    unit: 'kg',
    stock: 18,
    minStock: 3,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'काभ्रेको ताजा गोलभेंडा',
    brand: 'Local'
  },

  // Staples
  {
    id: 'prod-4',
    shopId: 'shop-1',
    aliasId: 'sugar',
    nameNe: 'चिनी (सेतो)',
    nameEn: 'White Sugar',
    category: 'staples',
    price: 90,
    unit: 'kg',
    stock: 45,
    minStock: 8,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1581441363689-1f3c3c414635?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'सफा र उच्च गुणस्तरको चिनी',
    brand: 'Everest Sugar'
  },
  {
    id: 'prod-5',
    shopId: 'shop-1',
    aliasId: 'rice',
    nameNe: 'जिरा मसिना चामल',
    nameEn: 'Jeera Masino Rice',
    category: 'staples',
    price: 110,
    unit: 'kg',
    stock: 60,
    minStock: 10,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'मिठो बास्नादार जिरा मसिना चामल',
    brand: 'Aarati Rice'
  },
  {
    id: 'prod-6',
    shopId: 'shop-1',
    aliasId: 'lentil',
    nameNe: 'मुसुरो दाल (दलेको)',
    nameEn: 'Red Lentils (Musuro Dal)',
    category: 'staples',
    price: 160,
    unit: 'kg',
    stock: 25,
    minStock: 5,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1585994192701-f1a505c817ea?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'छिटो पाक्ने स्वादिष्ट रातो मुसुरो दाल',
    brand: 'Shakti Dal'
  },
  {
    id: 'prod-7',
    shopId: 'shop-1',
    aliasId: 'oil',
    nameNe: 'धारा तोरीको तेल',
    nameEn: 'Dhara Mustard Oil',
    category: 'staples',
    price: 180,
    unit: 'litre',
    stock: 30,
    minStock: 6,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'शुद्ध तोरीको तेल, १००% शुद्ध',
    brand: 'Dhara'
  },
  {
    id: 'prod-8',
    shopId: 'shop-1',
    aliasId: 'flour',
    nameNe: 'गहुँको पिठो (आटा)',
    nameEn: 'Fresh Wheat Atta',
    category: 'staples',
    price: 75,
    unit: 'kg',
    stock: 40,
    minStock: 8,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'चक्कीमा पिसेको शुद्ध गहुँको पिठो',
    brand: 'Fortune'
  },
  {
    id: 'prod-9',
    shopId: 'shop-1',
    aliasId: 'salt',
    nameNe: 'आयो नुन (Iodized Salt)',
    nameEn: 'Aayo Salt Packet',
    category: 'spices',
    price: 30,
    unit: 'packet',
    stock: 50,
    minStock: 10,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'साल्ट ट्रेडिङ कर्पोरेसनको आयोडिनयुक्त नुन',
    brand: 'Salt Trading'
  },

  // Dairy
  {
    id: 'prod-10',
    shopId: 'shop-1',
    aliasId: 'milk',
    nameNe: 'डिडिसी गाईको ताजा दूध (DDC)',
    nameEn: 'DDC Cow Fresh Milk',
    category: 'dairy',
    price: 60,
    unit: 'packet',
    stock: 22,
    minStock: 5,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'ताजा र पोषिलो पाश्चराइज्ड दूध (५०० मि.लि.)',
    brand: 'DDC'
  },
  {
    id: 'prod-11',
    shopId: 'shop-1',
    aliasId: 'egg',
    nameNe: 'ताजा अन्डा (१ क्रेट / ३० वटा)',
    nameEn: 'Fresh Farm Eggs (30 pcs)',
    category: 'dairy',
    price: 450,
    unit: 'box',
    stock: 12,
    minStock: 2,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'पोल्ट्री फार्मबाट सिधै आएको ताजा अण्डा',
    brand: 'Valley Farm'
  },

  // Snacks & Beverages
  {
    id: 'prod-12',
    shopId: 'shop-1',
    aliasId: 'noodles',
    nameNe: 'वाइवाइ तयारी चाउचाउ',
    nameEn: 'Wai Wai Instant Noodles (75g)',
    category: 'snacks',
    price: 25,
    unit: 'packet',
    stock: 65,
    minStock: 15,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'नेपालको मनपर्ने स्वादिलो चाउचाउ',
    brand: 'CG Foods Wai Wai'
  },
  {
    id: 'prod-13',
    shopId: 'shop-1',
    aliasId: 'tea',
    nameNe: 'टोक्ला सीटीसी चियापत्ती (५०० ग्राम)',
    nameEn: 'Tokla CTC Tea (500g)',
    category: 'beverages',
    price: 220,
    unit: 'packet',
    stock: 18,
    minStock: 3,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'कडक र सुगन्धित झापाको सीटीसी चिया',
    brand: 'Tokla'
  },
  {
    id: 'prod-14',
    shopId: 'shop-1',
    aliasId: 'biscuits',
    nameNe: 'पारले-जी ग्लुकोज बिस्कुट',
    nameEn: 'Parle-G Glucose Biscuit',
    category: 'snacks',
    price: 20,
    unit: 'packet',
    stock: 45,
    minStock: 10,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'चियासँग खान उत्तम ग्लुकोज बिस्कुट',
    brand: 'Parle'
  },

  // Household
  {
    id: 'prod-15',
    shopId: 'shop-1',
    aliasId: 'soap',
    nameNe: 'लाइफब्वाय साबुन (Lifebuoy)',
    nameEn: 'Lifebuoy Bath Soap',
    category: 'household',
    price: 45,
    unit: 'piece',
    stock: 32,
    minStock: 5,
    isAvailable: true,
    image: 'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'कीटाणुबाट १००% सुरक्षा दिने साबुन',
    brand: 'Unilever Lifebuoy'
  },

  // ── Sweet shop (shop-4) ──
  {
    id: 'prod-s1', shopId: 'shop-4', aliasId: 'laddu', nameNe: 'लड्डु (बेसन)', nameEn: 'Besan Laddu',
    category: 'sweets', price: 600, unit: 'kg', stock: 15, minStock: 3, isAvailable: true,
    image: 'https://images.unsplash.com/photo-1666190092159-3171cf0fbb12?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'ताजा बेसनको स्वादिष्ट लड्डु', brand: 'घरेलु'
  },
  {
    id: 'prod-s2', shopId: 'shop-4', aliasId: 'barfi', nameNe: 'बर्फी (खुवा)', nameEn: 'Khuwa Barfi',
    category: 'sweets', price: 750, unit: 'kg', stock: 12, minStock: 3, isAvailable: true,
    image: 'https://images.unsplash.com/photo-1605197161470-5d2a9af0ac7e?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'शुद्ध खुवाको बर्फी', brand: 'घरेलु'
  },
  {
    id: 'prod-s3', shopId: 'shop-4', aliasId: 'rasgulla', nameNe: 'रसगुल्ला', nameEn: 'Rasgulla',
    category: 'sweets', price: 400, unit: 'kg', stock: 20, minStock: 4, isAvailable: true,
    image: 'https://images.unsplash.com/photo-1601303516361-f8a7e2b8f4a4?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'रसिलो नरम रसगुल्ला', brand: 'घरेलु'
  },
  {
    id: 'prod-s4', shopId: 'shop-4', aliasId: 'jerry', nameNe: 'जेरी (जलेबी)', nameEn: 'Jerry / Jalebi',
    category: 'sweets', price: 350, unit: 'kg', stock: 18, minStock: 4, isAvailable: true,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'कुरकुरे ताजा जेरी', brand: 'घरेलु'
  },
  {
    id: 'prod-s5', shopId: 'shop-4', aliasId: 'samosa', nameNe: 'समोसा', nameEn: 'Samosa',
    category: 'namkeen', price: 25, unit: 'piece', stock: 60, minStock: 10, isAvailable: true,
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'तातो कुरकुरे आलु समोसा', brand: 'घरेलु'
  },
  {
    id: 'prod-s6', shopId: 'shop-4', aliasId: 'cake', nameNe: 'क्रिम केक (आधा किलो)', nameEn: 'Cream Cake (0.5kg)',
    category: 'bakery', price: 550, unit: 'piece', stock: 8, minStock: 2, isAvailable: true,
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'नरम स्वादिष्ट क्रिम केक', brand: 'बेकरी'
  },

  // ── Hardware store (shop-5) ──
  {
    id: 'prod-h1', shopId: 'shop-5', aliasId: 'hammer', nameNe: 'हथौडा', nameEn: 'Hammer',
    category: 'tools', price: 450, unit: 'piece', stock: 14, minStock: 3, isAvailable: true,
    image: 'https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'बलियो स्टिल हथौडा', brand: 'Taparia'
  },
  {
    id: 'prod-h2', shopId: 'shop-5', aliasId: 'nails', nameNe: 'किला (२ इन्च)', nameEn: 'Nails (2 inch)',
    category: 'fasteners', price: 150, unit: 'kg', stock: 40, minStock: 8, isAvailable: true,
    image: 'https://images.unsplash.com/photo-1609205807107-e8ec2120f9de?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'जस्ता लगाइएको किला', brand: 'Local'
  },
  {
    id: 'prod-h3', shopId: 'shop-5', aliasId: 'paint', nameNe: 'दिवाल पेन्ट (सेतो, ४ लि.)', nameEn: 'Wall Paint (White, 4L)',
    category: 'paint', price: 1250, unit: 'bottle', stock: 10, minStock: 2, isAvailable: true,
    image: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'चम्किलो सेतो इमल्सन पेन्ट', brand: 'Asian Paints'
  },
  {
    id: 'prod-h4', shopId: 'shop-5', aliasId: 'wire', nameNe: 'बिजुली तार (९० मिटर)', nameEn: 'Electric Wire (90m)',
    category: 'electrical', price: 2200, unit: 'box', stock: 9, minStock: 2, isAvailable: true,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'तामाको सुरक्षित बिजुली तार', brand: 'CG'
  },
  {
    id: 'prod-h5', shopId: 'shop-5', aliasId: 'bulb', nameNe: 'एलईडी बल्ब (९ वाट)', nameEn: 'LED Bulb (9W)',
    category: 'electrical', price: 180, unit: 'piece', stock: 50, minStock: 10, isAvailable: true,
    image: 'https://images.unsplash.com/photo-1550985616-10810253b84d?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'बिजुली बचत गर्ने एलईडी बल्ब', brand: 'Philips'
  },
  {
    id: 'prod-h6', shopId: 'shop-5', aliasId: 'pipe', nameNe: 'पीभीसी पाइप (१ इन्च)', nameEn: 'PVC Pipe (1 inch)',
    category: 'plumbing', price: 320, unit: 'piece', stock: 25, minStock: 5, isAvailable: true,
    image: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=400&auto=format&fit=crop&q=80',
    descriptionNe: 'बलियो पानी पाइप', brand: 'Jagdamba'
  }
];

export const INITIAL_ORDERS = [
  {
    id: 'ORD-9101',
    shopId: 'shop-1',
    customerName: 'हरि प्रसाद दवाडी',
    customerPhone: '9841998877',
    orderType: 'delivery', // 'delivery' | 'pickup'
    deliveryAddress: 'मध्य बानेश्वर, घर नं. ४५, काठमाडौं',
    distanceKm: 1.2,
    items: [
      { productId: 'prod-1', nameNe: 'आलु (लोकल)', nameEn: 'Potato', quantity: 2, unit: 'kg', price: 80 },
      { productId: 'prod-4', nameNe: 'चिनी (सेतो)', nameEn: 'Sugar', quantity: 1, unit: 'kg', price: 90 },
      { productId: 'prod-12', nameNe: 'वाइवाइ चाउचाउ', nameEn: 'Wai Wai', quantity: 4, unit: 'packet', price: 25 },
    ],
    itemsSubtotal: 350,
    deliveryCharge: 35,
    grandTotal: 385,
    paymentMethod: 'esewa', // 'cod' | 'esewa' | 'khalti' | 'bankTransfer'
    paymentStatus: 'paid',
    orderStatus: 'preparing', // 'received' | 'accepted' | 'preparing' | 'out_for_delivery' | 'delivered' | 'rejected'
    statusStep: 3,
    assignedRider: 'रमेश (Ramesh - 9801122334)',
    locationPermissionGranted: true,
    lat: 27.695,
    lng: 85.340,
    createdAt: new Date(Date.now() - 25 * 60000).toISOString(),
    customerNote: 'गेटमा आइपुगेपछि फोन गर्नुहोला।'
  },
  {
    id: 'ORD-9098',
    shopId: 'shop-1',
    customerName: 'सरिता गुरुङ',
    customerPhone: '9860112233',
    orderType: 'pickup',
    deliveryAddress: 'पसलबाट लिन आउने',
    distanceKm: 0,
    items: [
      { productId: 'prod-5', nameNe: 'जिरा मसिना चामल', nameEn: 'Rice', quantity: 5, unit: 'kg', price: 110 },
      { productId: 'prod-7', nameNe: 'धारा तोरीको तेल', nameEn: 'Oil', quantity: 2, unit: 'litre', price: 180 },
    ],
    itemsSubtotal: 910,
    deliveryCharge: 0,
    grandTotal: 910,
    paymentMethod: 'cod',
    paymentStatus: 'pending',
    orderStatus: 'delivered',
    statusStep: 5,
    assignedRider: 'पसले आफैं',
    locationPermissionGranted: false,
    createdAt: new Date(Date.now() - 140 * 60000).toISOString(),
    customerNote: ''
  }
];

export const INITIAL_EXPENSES = [
  {
    id: 'exp-1',
    shopId: 'shop-1',
    title: 'डेलिभरी बाइक पेट्रोल',
    amount: 300,
    date: new Date().toISOString().split('T')[0],
    category: 'Delivery'
  },
  {
    id: 'exp-2',
    shopId: 'shop-1',
    title: 'पसलको बिजुली महसुल',
    amount: 450,
    date: new Date().toISOString().split('T')[0],
    category: 'Utilities'
  }
];

// Pre-packaged generic stock images for AI suggestion generator
export const GENERIC_PRODUCT_IMAGES = {
  potato: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&auto=format&fit=crop&q=80',
  onion: 'https://images.unsplash.com/photo-1508747703725-719777637510?w=400&auto=format&fit=crop&q=80',
  tomato: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400&auto=format&fit=crop&q=80',
  sugar: 'https://images.unsplash.com/photo-1581441363689-1f3c3c414635?w=400&auto=format&fit=crop&q=80',
  rice: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&auto=format&fit=crop&q=80',
  oil: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&auto=format&fit=crop&q=80',
  milk: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&auto=format&fit=crop&q=80',
  lentil: 'https://images.unsplash.com/photo-1585994192701-f1a505c817ea?w=400&auto=format&fit=crop&q=80',
  salt: 'https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?w=400&auto=format&fit=crop&q=80',
  tea: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400&auto=format&fit=crop&q=80',
  noodles: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=400&auto=format&fit=crop&q=80',
  soap: 'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=400&auto=format&fit=crop&q=80',
  biscuit: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&auto=format&fit=crop&q=80',
  egg: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400&auto=format&fit=crop&q=80',
  general: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&auto=format&fit=crop&q=80'
};
